### ISSUE TITLE
library name collision

### ISSUE THREAD

**Issue by CaeruleusAqua** [sciplot/sciplot#29]
When trying to get the port into vcpkg, I was told that there is already a library called sciplot on Linux.
Since the current naming scheme causes collisions, they suggested renaming the library to allanleal-sciplot.
It should be enough to rename the cmake target (and file name) and the include directory.

I can handle that, but please give me some feedback.

**Comment by allanleal** [comment]
OK, that's unfortunate. I found the PR you created there. It seems there is this old project:

https://packages.debian.org/buster/libsciplot-dev

I'll reply there and see if we can go with `sciplot`, because this is not the same name as `libsciplot-dev`, and there should not be confusion if the packages are clearly defined.

**Comment by allanleal** [comment]
Hi @CaeruleusAqua , I'll close this issue here as we are dealing with it here instead: https://github.com/microsoft/vcpkg/pull/15913
