### ISSUE TITLE
No PlotSpec::use() option anymore

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#45]
Am I mistaken, or was this lost on the way to 0.2?
You could call
```c++
Plot p;
p.draw(x,y).use(sciplot::plotspecs::USE_AUTO, 2, sciplot::plotspecs::USE_AUTO, 1);
```
Is there an equivalent or should I add something?

**Comment by allanleal** [comment]
We don't need this `using` concept of gnuplot anymore because we now have methods like this:

~~~c++
p.drawCurve("file.dat", 6, 3); // x from column 6, y from column 3
p.drawBoxes("file.dat", 7, 2, 8); // x from column 7, y from column 2, xwidths from column 8
~~~

For the specific use case you put above, we can just use:

~~~c++
Plot p;
p.drawCurve(y, x);
~~~

Let me know if there are use cases in which the `drawSomething(filename, xcol, ycol, ...)` is not sufficient.

**Comment by allanleal** [comment]
This needs to be better documented (these methods using data files and column indices).

**Comment by HorstBaerbel** [comment]
Thanks. The default works in my case.
