### ISSUE TITLE
FillSpecsOf and FillStyleSpecs are duplicate

### ISSUE THREAD

**Issue by HorstBaerbel** [sciplot/sciplot#60]
Which one is correct? Which one can be deleted?
@allanleal I can fix this. Just tell me which of those you intended to use. Currently they are both used, which I think is unnecessary code bloat and user confusion.

**Comment by allanleal** [comment]
Just saw this now. I now remember why this. 

`FillSpecsOf` is used to set the fill style of plotted elements (e.g., boxes in a `drawBoxes(x, y).fillSolid().fillColor("red")`). 

`FillStyleSpecs` is to set general fill style for a `Plot`/`Figure` object to mimic the gnuplot command `set style fill ...`. Example: `plot.styleFill().solid();`.

**Comment by HorstBaerbel** [comment]
The strings generated seem to be the same to me....

**Comment by allanleal** [comment]
If we go with `FillSpecsOf` only (deleting `FillStyleSpecs`, which is applicable for `Plot`, and not `DrawSpecs` of a `drawXYZ` method) then we'll end up with redundant method names:

~~~c++
Plot plot;
plot.styleFill().fillSolid().fillIntensity(0.5).fillColor("red");
~~~

instead of

~~~c++
Plot plot;
plot.styleFill().solid().intensity(0.5);
~~~

**More important:** `FillSpecsOf` has `fillColor` whereas `FillStyleSpecs` **do not**. This is because, again, `FillStyleSpecs` allows common fill specifications for all plot elements in the `Plot` object. In gnuplot, `set style fill ...` does not support setting common color for all plotted elements.

The `FillStyleSpecs` also makes a good parallel with the `HistogramStyleSpecs`.

**Comment by HorstBaerbel** [comment]
So they are "FigureFillSpec" and "PlotFillSpec"?
